Accept=Onartu
Close=Itxi
Price= Prezioa
SelectOption=Aukeratu
Status=Egoera

MainGUI.Login= Hasi saioa
MainGUI.Register= Konturik ez baduzu, klikatu hemen erregistratzeko
MainGUI.Title= AZOKA DIGITALA
MainGUI.SelectOption=AZOKA DIGITALA
 
MainGUIErregistratua.MenuMerkatua=Merkatua
MainGUIErregistratua.MenuNireEremua=Nire eremua
MainGUIErregistratua.MenuDiruZorroa=Diru-zorroa
MainGUIErregistratua.MenuNotifikazioak=Notifikazioak
MainGUIErregistratua.SelectOption=Aukeratu
MainGUIErregistratua.Logout=Amaitu saioa
MainGUIErregistratua.MainTitle=Erregistratutako erabiltzailea
MainGUIErregistratua.CreateSale=Sortu eskaintza
MainGUIErregistratua.QuerySales=Eskaintzak bilatu
MainGUIErregistratua.QueryFavorites=Nire gogokoenak
MainGUIErregistratua.QueryBought=Nire erosketak
MainGUIErregistratua.QueryMovements=Ikusi mugimenduak
MainGUIErregistratua.Wallet=Diru-zorroa kudeatu
MainGUIErregistratua.QueryReports=Nire salaketak
MainGUIErregistratua.QueryErreklamazioak=Nire erreklamazioak
MainGUIErregistratua.QueryNotifikazioak=Nire notifikazioak
MainGUIErregistratua.EskaeraSortu=Eskaera Sortu
MainGUIErregistratua.QueryEskaerak= Ikusi eskaerak
MainGUIErregistratua.EskaeraErantzun= Eskaera erantzun
MainGUIErregistratua.QueryEskaintza= Eskaintzak
MainGUIErregistratua.QueryNireEskaerak= Nire eskaerak

CreateSaleGUI.Title=Tituloa:
CreateSaleGUI.Description=Deskripzioa:
CreateSaleGUI.Status=Egoera:
CreateSaleGUI.Category=Kategoria:
CreateSaleGUI.Price=Prezioa:
CreateSaleGUI.PriceMustBeGreaterThan0=ERROR, prezioa 0 baino handiagoa
CreateSaleGUI.ProductCreated=Eskaintza sortuta
CreateSaleGUI.CreateProduct=Sortu Eskaintza
CreateSaleGUI.ErrorNumber=Error, prezioa zenbaki bat izan behar da
CreateSaleGUI.ErrorQuery=Error, datuak falta dira
CreateSaleGUI.LoadPicture=Argazkia igo
CreateSaleGUI.PublicationDate=Argitarapen eguna:
CreateSaleGUI.Category=Kategoria:

QuerySalesGUI.Search=Bilatu
QuerySalesGUI.NoProducts=Ez daude eskaintzak
QuerySalesGUI.Price=Prezioa
QuerySalesGUI.FindProducts=Eskaintzak bilatu
QuerySalesGUI.Products=Eskaintzak (Double-click eskaintza ikusteko)

ShowSaleGUI.Title=Eskaintza xehestasunak


DataAccess.SaleAlreadyExist=ERROR, Eskaintza existizen da
DataAccess.ErrorSaleMustBeLaterThanToday=ERROR, data gaur baino beranduago izan behar da
DataAccess.ErrorFileNotUploadedException=ERROR, Argazkia igo behar da
DataAccess.NahikoDirurikEzException= ERROR, ez duzu nahiko dirurik

RegisteredGUI.email=Posta elektronikoa:
RegisteredGUI.password=Pasahitza:
RegisteredGUI.passwordrepeat=Errepikatu pasahitza:
RegisteredGUI.Register=Erregistratu
RegisteredGUI.registError= Erabiltzaile hau jada erregistratuta dago
RegisteredGUI.differentPasswords= Pasahitzak berdinak izan behar dira
RegisteredGUI.blankData= Datu guztiak beteta egon behar dira
RegisteredGUI.txartelIzena= Txartel izena:
RegisteredGUI.txartelZenbakia= Txartel zenbakia:
RegisteredGUI.PIN= PIN:
RegisteredGUI.numberError= Txartel zenbakia eta PIN-a zenbakiak izan behar dira

LoginGUI.email=Posta elektronikoa:
LoginGUI.password=Pasahitza:
LoginGUI.Login=Hasi saioa
LoginGUI.ErroreMezua=Email edo pasahitza oker daude

QueryFavourites.add=Gehitu gogokoen produktuetara

MainGUIErregistratua.buy=erosi produktu bat

BuyGUI.cardName=Txartel Izena
BuyGUI.cardPin=Txartelaren Pin-a
BuyGUI.cardNumber=Txartel Zenbakia
BuyGUI.buy=Erosi

ShowSaleGUI.buy=Erosi
ShowSaleGUI.favorite=Gorde
ShowSaleBoughtGUI.claim=Erreklamatu

QueryBoughtGUI.name=Erositako objektuak

QueryMugimenduakGUI.name= Mugimendu guztiak
QueryBoughtGUI.name=Erositako objektuak

Wallet.Balance=Saldoa

WalletGUI.Title=Diru-zorroa
WalletGUI.Amount=Kantitatea
WalletGUI.Pin=PIN
WalletGUI.PinError=PIN okerra
WalletGUI.NumberError=Zenbakiak bakarrik
WalletGUI.NoMoney=Ez dago nahiko dirurik
WalletGUI.Add=Gehitu
WalletGUI.Remove=Atera
WalletGUI.Negative=Dirua ezin da negatibo edo 0 izan

MainGUIErregistratuaArd.Complaint= SALAKETAK
MainGUIErregistratuaArd.Claim= ERREKLAMAZIOAK

OfertaSalatuGUI.title= Titulua
OfertaSalatuGUI.description= Deskribapena:
OfertaSalatuGUI.report= Salatu

ErreklamatuGUI.title= Titulua
ErreklamatuGUI.description= Deskribapena: 
ErreklamatuGUI.claim= Erreklamatu
ErreklamatuGUI.error= Jada erreklamatua izan da

QuerySalaketakGUI.name= Salaketak

SalaketaIkusiGUI.Accept= Onartu
SalaketaIkusiGUI.Reject= Ezeztatu

SalaketaIkusiGUI.accepted= Salaketa onartua
SalaketaIkusiGUI.rejected= Salaketa ezeztatua
SalaketaIkusiGUI.alreadyDeleted= Produktua jada ezabatua izan da

QuerySalaketakGUI.name= Salaketak

QueryErreklamazioakGUI.name=Erreklamazioak

ErreklamazioaIkusiGUI.accepted= Salaketa onartua
ErreklamazioaIkusiGUI.rejected= Salaketa ezeztatua
ErreklamazioaIkusiGUI.alreadyDeleted= Produktua jada ezabatua izan da

KategoriakGUI.title= Gogokoen dituzun kategoriak aukeratu
KategoriakGUI.botoia= Egina

QueryNotifikazioakGUI.name= Notifikazioak

ShowSaleGUI.multipleBuy = Saltzailearen produktu gehiago

QueryMultipleSalesGUI.FindProducts = Saltzailearen produktu guztiak
QueryMultipleSalesGUI.EndBuy=Erosketa Amaitu
QueryMultipleSalesGUI.LabelSaldoa=Zure Saldoa
QueryMultipleSalesGUI.BuyButton=Hautatutakoa Ordaindu
QueryMultipleSalesGUI.Select=Hautatu
QueryMultipleSalesGUI.ErrorNoSelect=Ez duzu artikulurik hautatu ordaintzeko.
QueryMultipleSalesGUI.Success=Erosketa ongi burutu da!
NahikoDirurikEzException=Ez duzu nahiko diru saldoan erosketa hau egiteko.

EskaeraSortuGUI.productName= Produktuaren izena
EskaeraSortuGUI.produktuKategoria= Produktuaren kategoria
EskaeraSortuGUI.mezua= Eskaera sortu da

QueryEskaerak.Products=Eskaerak (Double-click eskaera erantzuteko)
<<<<<<< HEAD

MainGUIErregistratua.NireEskaerak=Nire eskaerak
=======
EskaeraErantzunGUI.answer=Erantzun mezua
EskaeraErantzunGUI.mezua= Erantzuna ondo bidali da
>>>>>>> 2debbb810abd5ed534759a297b2a3f2ca53a7f69
